app/financedb/apps/asset/urls.py
from django.urls import path
from . import views as v

app_name = 'asset'


urlpatterns = [

    path('serverside/', v.assets_serverside,
         name='url_assets_serverside'),
    path('list/', v.list_assets, name='url_list_assets'),
    path('detail/<str:pk>/', v.detail_asset, name='url_asset_detail'),
    path('update/<str:pk>/', v.update_asset, name='url_update_asset'),
    path('delete/<str:pk>/', v.delete_asset, name='url_delete_asset'),
    path('new/', v.new_asset, name='url_new_asset'),
    path('json/', v.assets_json, name='url_assets_json'),

]

app/financedb/apps/core/urls.py
from django.urls import path
from . import views as v

app_name = 'core'


urlpatterns = [

    path('', v.home, name='home'),

    path('time/', v.current_datetime),
    path('upload_file/', v.upload_file, name='url_upload_file'),

]

app/financedb/apps/portfolio/urls.py
from django.urls import include, path
from . import views as v

app_name = 'portfolio'


# entrada_patterns = [
#     path('', v.EstoqueEntradaList.as_view(), name='estoque_entrada_list'),
#     path('add/', v.estoque_entrada_add, name='estoque_entrada_add'),
# ]

# saida_patterns = [
#     path('', v.EstoqueSaidaList.as_view(), name='estoque_saida_list'),
#     path('add/', v.estoque_saida_add, name='estoque_saida_add'),
# ]

urlpatterns = [

    path('list', v.list_portfolio, name='url_list_portfolio'),
    # path('<int:pk>/', v.EstoqueDetail.as_view(), name='estoque_detail'),
    # path('entrada/', include(entrada_patterns)),
    # path('saida/', include(saida_patterns)),
]

app/financedb/apps/transaction/urls.py
from django.urls import path
from . import views as v

app_name = 'transaction'


urlpatterns = [

    path('list/', v.list_transactions,
         name='url_list_transactions'),
    path('new/', v.Create_transaction.as_view(),
         name='url_new_transaction'),
    path('update/<int:pk>/',
         v.Update_transaction.as_view(), name='url_update_transaction'),
    path('detail/<int:pk>/',
         v.detail_transaction, name='url_detail_transaction'),
    path('delete/<int:pk>/',
         v.delete_transaction, name='url_delete_transaction'),

    path('test/', v.test, name='url_test'),
    path('serverside/', v.transactions_serverside,
         name='url_transactions_serverside'),
    path('json/', v.transactions_json,
         name='url_transactions_json'),


]

app/financedb/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('', include('financedb.apps.core.urls')),
    path('asset/', include('financedb.apps.asset.urls')),
    path('transaction/', include('financedb.apps.transaction.urls')),
    path('portfolio/', include('financedb.apps.portfolio.urls')),

    path('admin/', admin.site.urls),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

app/financedb/apps/core/models.py
from django.db import models
# from django.urls import reverse_lazy


class TimeStampedModel(models.Model):
    created = models.DateTimeField(
        'criado em',
        auto_now_add=True, auto_now=False
    )
    modified = models.DateTimeField(
        'modificado em',
        auto_now_add=False, auto_now=True
    )

    class Meta:
        abstract = True

# Create your models here.

app/financedb/apps/core/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core.files.storage import FileSystemStorage
import datetime


def current_datetime(request):
    now = datetime.datetime.now()
    html = "<html><body>It is now %s.</body></html>" % now
    return HttpResponse(html)


def upload_file(request):
    url = []
    if request.method == 'POST':
        uploaded_file = request.FILES['document']
        fs = FileSystemStorage()
        name = fs.save(uploaded_file.name, uploaded_file)
        url = fs.url(name)
        print(url)
    return render(request, 'core/upload_file.html', {'url': url})  #


def home(request):
    return render(request, 'core/home.html', {'now': datetime.datetime.now()})

app/financedb/apps/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="https://getbootstrap.com/favicon.ico">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css">
  <link rel="stylesheet" href="https://cdn.datatables.net/1.10.23/css/jquery.dataTables.min.css">
  <!-- Font-awesome -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">


  <title>FinanceDB</title>

  <style>
    .ok {
      color: green; 
    }
    .no {
      color: red;
    }
    span.required:after { 
      content: "*"; 
      color: red;
    }
  </style>
</head>
<body>
    {% include "core/nav.html" %}
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-20 col-md-12">
          <div class="card mb-4">
            <div class="card-body">
              <main role="main">

              {% block content %}{% endblock content %}

              </main> 
              {% comment %} {% block content %}{% endblock %} {% endcomment %}
            </div>
          </div>
        </div>
      </div>
    </div>
    {% comment %} <main role="main">

    {% block content %}{% endblock content %}

    </main> {% endcomment %}

    <footer class="container">
      <p>&copy; Company 2021</p>
    </footer>

  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
  <script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>


  {% block js %}{% endblock js %}
</body>
</html>

app/financedb/apps/core/templates/core/base_old.html
{% load static %}
<!-- https://getbootstrap.com/docs/4.0/getting-started/introduction/#starter-template -->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="https://getbootstrap.com/favicon.ico">

  {% comment %} <link rel="shortcut icon" href="https://www.djangoproject.com/favicon.ico"> {% endcomment %}
  <!-- <link rel="shortcut icon" href="http://html5-training-in-hyderabad.blogspot.com.br/favicon.ico"> -->
  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css">
  <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">

  {% comment %} <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> {% endcomment %}
  {% comment %} <link rel="stylesheet" type="text/css" href="{% static 'css/app.css' %}"> {% endcomment %}

  {% comment %} <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"> {% endcomment %}
  <!-- Font-awesome -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <style>
    .ok {
      color: green; 
    }
    .no {
      color: red;
    }
    span.required:after { 
      content: "*"; 
      color: red;
    }
    </style> 

  {% block css %}{% endblock css %}
  <title>{% block title %}FinanceDB{% endblock %}</title>
</head>

<body>
  {% include "core/nav.html" %}
  {% comment %} <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-10 col-md-12">
        <div class="card mb-4">
          <div class="card-body">
            {% block content %}{% endblock %}
          </div>
        </div>
      </div>
    </div>
  </div> {% endcomment %}

  <main role="main">

  {% block content %}{% endblock content %}

  </main>

  <footer class="container">
    <p>&copy; Company 2021</p>
  </footer>


  <!-- jQuery first, then Popper.js, dataTables, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.js"></script>

  {% comment %} <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> {% endcomment %}
  {% comment %} <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script> {% endcomment %}

  <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  {% block js %}{% endblock js %}

</body>
</html>

app/financedb/apps/core/templates/core/bau.html
{% extends "website/_layouts/base.html" %}

<!-- Bloco que define o <title></title> da nossa página -->
{% block title %}Página Inicial{% endblock %}

<!-- Bloco de conteúdo da nossa página -->    
{% block conteudo %}
<div class="container">
  <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Cadastrar Funcionário</h5>
          <p class="card-text">
            Cadastre aqui um novo <code>Funcionário</code>.
          </p>
          <a href="{% url 'website:cadastra_funcionario' %}"
             class="btn btn-primary">
            Novo Funcionário
          </a>
        </div>
      </div>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Lista de Funcionários</h5>
          <p class="card-text">
            Veja aqui a lista de <code>Funcionários</code> cadastrados.
          </p>
          <a href="{% url 'website:lista_funcionarios' %}"
             class="btn btn-primary">
            Vá para Lista
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/financedb/apps/core/templates/core/home.html
{% extends "core/base.html" %}

{% block content %}

<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
  <div class="container">
    <h1>Welcome to FinanceDB!</h1>
    <p>This is a introduction to Django.</p>
    <p>Agora são: {{now}}</p>
    <p>
      <a href="">
        <button class="btn btn-primary btn-lg" type="button">
          Cadastrar <span class="fa fa-plus"></span>
        </button>
      </a>
    </p>
  </div>
</div>

<div class="text-center mt-5 pt-5">
    <h1>Bootstrap starter template</h1>
    <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
</div>

{% endblock content %}

app/financedb/apps/core/templates/core/nav.html
<!-- https://getbootstrap.com/docs/4.0/examples/starter-template/ -->
<!-- https://github.com/JTruax/bootstrap-starter-template/blob/master/template/start.html -->

<nav class="navbar navbar-expand-lg navbar-light mb-4" style="background-color:#decdc3">
    <div class="container">
        <a class="navbar-brand" href="{% url 'core:home'%}">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link"
                     href="{% url 'core:home'%}">Home <span
                      class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" 
                     href="#" id="dropdown01" 
                     data-toggle="dropdown" 
                     aria-haspopup="true"
                     aria-expanded="false">Transações</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown01">
                        <a class="dropdown-item"
                         href="{% url 'transaction:url_list_transactions'%}">Listar</a>
                        <a class="dropdown-item"
                         href="{% url 'transaction:url_transactions_serverside'%}">Listar2</a>
                        <a class="dropdown-item"
                         href="{% url 'transaction:url_new_transaction'%}">Criar Novo</a>
                        <a class="dropdown-item"
                         href="{% url 'transaction:url_transactions_json'%}">Json</a>
                        <a class="dropdown-item"
                         href="{% url 'core:url_upload_file'%}">Upload arquivo</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" 
                        href="#" id="dropdown01" 
                        data-toggle="dropdown" 
                        aria-haspopup="true" 
                        aria-expanded="false">Ativos</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown01">
                        <a class="dropdown-item"
                         href="{% url 'asset:url_list_assets'%}">Listar</a>
                        <a class="dropdown-item"
                         href="{% url 'asset:url_assets_serverside'%}">Listar2</a>
                        <a class="dropdown-item"
                         href="{% url 'asset:url_new_asset'%}">Criar Novo</a>
                        <a class="dropdown-item"
                         href="{% url 'asset:url_assets_json'%}">Json</a>
                        <a class="dropdown-item"
                         href="{% url 'core:url_upload_file'%}">Upload arquivo</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" 
                        href="#" id="dropdown01" 
                        data-toggle="dropdown" 
                        aria-haspopup="true" 
                        aria-expanded="false">Portifolio</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown01">
                        <a class="dropdown-item"
                         href="{% url 'portfolio:url_list_portfolio'%}">Listar</a>
                        <a class="dropdown-item"
                         href="{% url 'portfolio:url_list_portfolio'%}">Listar2</a>
                        <a class="dropdown-item"
                         href="{% url 'asset:url_new_asset'%}">Criar Novo</a>
                        <a class="dropdown-item"
                         href="{% url 'asset:url_assets_json'%}">Json</a>
                        <a class="dropdown-item"
                         href="{% url 'core:url_upload_file'%}">Upload arquivo</a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

app/financedb/apps/core/templates/core/upload_file.html
{% extends 'core/base.html' %}

{% block content %}

  <h2>Upload</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="document">
    <button type="submit">Upload file</button>
  </form>
  {% if url %}
    <p>Uploaded file: <a href="#">{{ url }}</a></p>
  {% endif %}

{% endblock %}