app/financedb/apps/transaction/urls.py
from django.urls import path
from . import views as v

app_name = 'transaction'


urlpatterns = [

    path('list/', v.list_transactions,
         name='url_list_transactions'),
    path('new/', v.Create_transaction.as_view(),
         name='url_new_transaction'),
    path('update/<int:pk>/',
         v.Update_transaction.as_view(), name='url_update_transaction'),
    path('detail/<int:pk>/',
         v.detail_transaction, name='url_detail_transaction'),
    path('delete/<int:pk>/',
         v.delete_transaction, name='url_delete_transaction'),

    path('test/', v.test, name='url_test'),
    path('serverside/', v.transactions_serverside,
         name='url_transactions_serverside'),
    path('json/', v.transactions_json,
         name='url_transactions_json'),


]

app/financedb/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('', include('financedb.apps.core.urls')),
    path('asset/', include('financedb.apps.asset.urls')),
    path('transaction/', include('financedb.apps.transaction.urls')),
    path('portfolio/', include('financedb.apps.portfolio.urls')),

    path('admin/', admin.site.urls),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

app/financedb/apps/transaction/models.py
from django.db import models
from django.urls import reverse_lazy
from financedb.apps.asset.models import Asset
from financedb.apps.nota.models import Nota
from financedb.apps.core.models import TimeStampedModel

OPERATION_TYPE = (
    ('C', 'Compra'),
    ('V', 'Venda'),
    ('DT', 'Day Trade'),
    ('S/I', 'Split ou Inplit'),
    ('AT', 'Alteração Ticker'),
    ('BN', 'Bonificação'),
    ('AM', 'Amortização'),
    ('SUB', 'Compra de Subscrição'),
    ('V.SUB', 'Venda Direito Subscrição'),
    ('V.SOB', 'Venda de sobras de S/I ou Cisão'),
    ('CISÃO', 'Operação de cião de capital social'),
    ('EX.OPC', 'Venda ou Compra por Exercício de Opção'),
)

# Create your models here.


class Transaction(TimeStampedModel):
    """A model of a Transactions."""
    # id = models.IntegerField(primary_key=True) #models.AutoField(primary_key=True)
    asset = models.ForeignKey(
        Asset, related_name='asset', on_delete=models.CASCADE)
    date = models.DateField()
    operation = models.CharField(
        max_length=6, choices=OPERATION_TYPE, default='C')
    amount = models.DecimalField(
        max_digits=10, decimal_places=5, null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=5)
    commission = models.DecimalField(
        max_digits=10, decimal_places=5, null=True, blank=True)
    nota_id = models.ForeignKey(
        Nota, related_name='nota', on_delete=models.CASCADE)
    account_bank = models.CharField(max_length=45, null=True, blank=True)
    obs = models.CharField(max_length=200, null=True, blank=True)
    total = models.DecimalField(
        max_digits=10, decimal_places=5, null=True, blank=True)
    profit = models.DecimalField(
        max_digits=10, decimal_places=5, null=True, blank=True)
    last_update = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('date',)
        verbose_name = 'transaction'
        verbose_name_plural = 'transactions'

    def get_absolute_url(self):
        # retorna a url no formato /bands/1/
        return reverse_lazy('transaction:url_detail_transaction', kwargs={'pk': self.pk})

    def __str__(self):
        return str(self.pk)

    def to_dict_json(self):
        data = {
            'id': self.id,
            'asset': self.asset.sigla,
            'date': self.date,
            'operation': self.operation,
            'amount': self.amount,
            'price': self.price,
            'nota_id': self.nota_id.id,
            'account_bank': self.account_bank,
        }
        return data

app/financedb/apps/transaction/views.py
import math
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.views.generic import CreateView, UpdateView, ListView
from django.http import Http404
from .form import TransactionForm
from .models import Transaction
from .models import Asset

# Create your views here.


def test(request):
    # data['transactions'] = Transaction.objects.all()
    transactions = Transaction.objects.all()[:50]
    return render(request, 'index.html', {'objects': transactions})


def list_transactions(request):
    # data['transactions'] = Transaction.objects.all()
    transactions = Transaction.objects.all()
    return render(request, 'list_transactions.html', {'objects': transactions})


def detail_transaction(request, pk):
    try:
        transaction = Transaction.objects.get(pk=pk)
    except Transaction.DoesNotExist:
        raise Http404('transaction does not exist')
    return render(request, 'detail_transaction.html', {'object': transaction})


class Create_transaction(CreateView):
    model = Transaction
    template_name = 'new_transaction.html'
    form_class = TransactionForm


class Update_transaction(UpdateView):
    model = Transaction
    template_name = 'new_transaction.html'
    form_class = TransactionForm


def delete_transaction(request, pk):
    try:
        transaction = Transaction.objects.get(pk=pk)
    except Transaction.DoesNotExist:
        raise Http404('asset does not exist')
    transaction.delete()
    return redirect('url_list_assets')


def transactions_json(request):
    transactions = Transaction.objects.all()
    total = transactions.count()

    _start = request.GET.get('start')
    _length = request.GET.get('length')
    if _start and _length:
        start = int(_start)
        length = int(_length)
        page = math.ceil(start / length) + 1  # [opcional]
        per_page = length  # [opcional]

        transactions = transactions[start:start + length]

    data = [transaction.to_dict_json() for transaction in transactions]
    response = {
        'data': data,
        # 'page': page,  # [opcional]
        # 'per_page': per_page,  # [opcional]
        'recordsTotal': total,
        'recordsFiltered': total,
    }
    return JsonResponse(response)


def transactions_serverside(request):
    template_name = 'transactions_serverside.html'
    return render(request, template_name)

app/financedb/apps/transaction/templates/detail_transaction.html
{% extends "core/base.html"%}

{% block content %}

<a href="{% url 'transaction:url_list_transactions' %}">Voltar</a>

<h1>{{ object }}
  <span class="pull-right">
    <a href="{% url 'transaction:url_update_transaction' object.pk %}">
      <button type="button" class="btn btn-success">
        <span class="fa fa-pencil"></span> Editar
      </button>
    </a>
  </span>
</h1>

<div class="col-sm-6">
  <table class="table table-user-information">
    <tbody>
      <tr>
        <th class="text-right">Fluxo</th>
        <td>
          {% if object.amount >= "0" %}
            <i class="fa fa-check-circle ok"></i>
          {% else %}
            <i class="fa fa-minus-circle no"></i>
          {% endif %}
        </td>
      </tr>
      <tr>
        <th class="text-right">Id</th>
        <td>{{ object.id }}</td>
      </tr>
      <tr>
        <th class="text-right">Ativo</th>
        <td>{{ object.asset }}</td>
      </tr>
      <tr>
        <th class="text-right">Operação</th>
        <td>{{ object.operation }}</td>
      </tr>
      <tr>
        <th class="text-right">Data</th>
        <td>{{ object.date }}</td>
      </tr>
      <tr>
        <th class="text-right">Quantidade</th>
        <td>{{ object.amount }}</td>
      </tr>
      <tr>
        <th class="text-right">Preço</th>
        <td>R$ {{ object.price }}</td>
      </tr>
      <tr>
        <th class="text-right">Comissão</th>
        <td>R$ {{ object.commission }}</td>
      </tr>
      <tr>
        <th class="text-right">Obs</th>
        <td>R$ {{ object.obs }}</td>
      </tr>
      <tr>
        <th class="text-right">Nota</th>
        <td>{{ object.nota_id }}</td>
      </tr>
    </tbody>
  </table>
</div>

{% endblock content %}

app/financedb/apps/transaction/templates/index.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}

<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
  <div class="container">
    <h2>Exemplo do uso de <a href="https://datatables.net/" target="_blank">DataTables</a></h2>
    <p>Exemplo do uso de DataTables com Django.</p>
    <!-- <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p> -->
  </div>
</div>

<div class="container">
  <!-- Example row of columns -->
  {% comment %} <h2>Lista</h2> {% endcomment %}
  <div class="row">
    <table id="myTable1" class="table">
      <thead>
        <tr>
          <th>Id</th>
          <th>tipo</th>
          <th>Ativo</th>
          <th>Data</th>
          <th>Quantidade</th>
          <th>Preço</th>
        </tr>
      </thead>
      <tbody>
        {% for object in objects %}
          <tr>
            <td>{{ object.id }}</td>
            <td>{{ object.operation }}</td>
            <td>{{ object.asset }}</td>
            <td>{{ object.date }}</td>
            <td>{{ object.amount }}</td>
            <td>{{ object.price }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <hr>

</div> <!-- /container -->

{% endblock content %}

{% block js %}

<script src="{% static 'js/data.js' %}"></script>

{% endblock js %}

app/financedb/apps/transaction/templates/list_transactions.html
{% extends "core/base.html"%}
{% load static %}

{% block content %}

<div class="row">
  <div class="col-sm-6">
    <form action="." method="GET" class="form-inline">
      <input type="text" id="search" name="search" class="form-control" placeholder="Busca">
      <input type="submit" class="btn btn-primary" style="margin-left: 10px;" value="OK">
    </form>
  </div>
</div>

<div class="page-header">
  <h2>Lista de Transações Cadastradas
    <span class="pull-right">
      <a href="{% url 'transaction:url_new_transaction'%}">
        <button type="button" class="btn btn-primary">
          <span class="fa fa-plus"></span> Adicionar
        </button>
      </a>
    </span>
  </h2>

  {% if objects %}
    {% comment %} <h1>Lista de ativos cadastrados</h1> {% endcomment %}
    <table id="TransactionsTable" class="table table-striped">
      <thead>
        <tr>
          <th class="text-center">Tipo</th>
          <th class="text-center">Id</th>
          <th class="text-center">Ativo</th>
          <th class="text-center">Data</th>
          <th class="text-center">Quantidade</th>
          <th class="text-center">Preço</th>
          <th class="text-center">Banco</th>
          <th class="text-center">Nota</th>
        </tr>
      </thead>
      <tbody>
        {% for object in objects %}
          <tr>
            <td class="text-center">
              {% if object.operation == "C" or object.operation == "BN" %}
                <i class="fa fa-check-circle ok"></i>
              {% else %}
                <i class="fa fa-check-circle no"></i>
              {% endif %}            
            </td>
            <td> <a href="{{ object.get_absolute_url}}">{{object.id}}</a></td>
            <td class="text-center"> 
              <a href="{{ object.get_absolute_url}}">{{object.asset}}</a>
            </td>
            <td>{{object.date}}</td>
            <td>{{object.amount}}</td>
            <td>R$ <span class="pull-right" > {{object.price}}</span></td>
            <td class="text-center"> {{object.account_bank}}</td>
            <td class="text-center"> {{object.nota_id}}</td>
          </tr> 
        {% endfor %}
      </tbody>
    </table>

  {% else %}
    <p class="alert alert-warning">Sem itens na lista.</p>
  {% endif %}

</div>

{% endblock content %}

{% block js %}

<script src="{% static 'js/data.js' %}"></script>

{% endblock js %}

app/financedb/apps/transaction/templates/new_transaction.html
{% extends "core/base.html"%}

{% load static %}
{% load widget_tweaks %}

{% block content %}

<form method="POST" novalidate>
  {% csrf_token %}
  {% for field in form.visible_fields %}
    <div class="form-group{% if field.errors %} has-error {% endif%}">
      <label for="{{ field.id_for_label }}">
        {% if field.field.required %}
          <span class="required">{{ field.label }} </span>
        {% else %}
          {{ field.label }}
        {% endif %}
      </label>
      {% render_field field class="form-control" %}
      {% for error in field.errors %}
        <span class="text-muted">{{ error }}</span>
      {% endfor %}
    </div>
  {% endfor %}
  <button type="submit" class="btn btn-success">Cadastrar</button>
</form>

{% endblock content %}

{% block js %}

{% comment %} <script src="{% static 'js/produto.js' %}"></script> {% endcomment %}

{% endblock js %}

app/financedb/apps/transaction/templates/transactions_serverside.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}

<div class="jumbotron">
  <div class="container">
    <h2>Exemplo do uso de <a href="https://datatables.net/" target="_blank">DataTables</a></h2>
    <p>Exemplo do uso de DataTables em <a href="https://datatables.net/examples/data_sources/server_side.html" target="_blank">Server-side render processing</a> com Django.</p>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="cols">
      <h2>DataTables Server-side render </h2>
      <table id="TransactionsTable1" class="table">
        <thead>
          <tr>
            <th>Tipo</th>
            <th>Id</th>
            <th>Ativo</th>
            <th>Data</th>
            <th>Quantidade</th>
            <th>Preço</th>
            <th>Banco</th>
            <th>Nota</th>
          </tr>
        </thead>
      </table>
    </div>
  </div>

  <hr>

</div> <!-- /container -->

{% endblock content %}

{% block js %}

<script src="{% static 'js/data.js' %}"></script>

{% endblock js %}