app/financedb/apps/asset/urls.py
from django.urls import path
from . import views as v

app_name = 'asset'


urlpatterns = [

    path('serverside/', v.assets_serverside,
         name='url_assets_serverside'),
    path('list/', v.list_assets, name='url_list_assets'),
    path('detail/<str:pk>/', v.detail_asset, name='url_asset_detail'),
    path('update/<str:pk>/', v.update_asset, name='url_update_asset'),
    path('delete/<str:pk>/', v.delete_asset, name='url_delete_asset'),
    path('new/', v.new_asset, name='url_new_asset'),
    path('json/', v.assets_json, name='url_assets_json'),

]

app/financedb/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('', include('financedb.apps.core.urls')),
    path('asset/', include('financedb.apps.asset.urls')),
    path('transaction/', include('financedb.apps.transaction.urls')),
    path('portfolio/', include('financedb.apps.portfolio.urls')),

    path('admin/', admin.site.urls),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

app/financedb/apps/asset/models.py
from django.db import models
from django.urls import reverse_lazy

# Create your models here.


class Asset(models.Model):
    """A model of a asset."""
    sigla = models.CharField(max_length=45, unique=True, primary_key=True)
    symbol = models.CharField(max_length=45, null=True, blank=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    isin = models.CharField(max_length=45, null=True, blank=True)
    classe = models.CharField(max_length=45, null=True, blank=True)
    market_cod = models.CharField(max_length=45, null=True, blank=True)
    market = models.CharField(max_length=45, null=True, blank=True)
    price = models.DecimalField(
        max_digits=10, decimal_places=5, null=True, blank=True)
    setor = models.CharField(max_length=45, null=True, blank=True)
    subsetor = models.CharField(max_length=45, null=True, blank=True)
    segmento = models.CharField(max_length=45, null=True, blank=True)
    codcvm = models.CharField(max_length=15, null=True, blank=True)
    cnpj = models.CharField(max_length=45, null=True, blank=True)
    razao_social = models.CharField(max_length=100, null=True, blank=True)
    cnpj_adm = models.CharField(max_length=45, null=True, blank=True)
    razao_social_adm = models.CharField(max_length=100, null=True, blank=True)
    last_update = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('sigla',)
        verbose_name = 'Asset'
        verbose_name_plural = 'Assets'

    def __str__(self):
        return self.sigla

    def get_absolute_url(self):
        # retorna a url no formato /bands/1/
        return reverse_lazy('asset:url_asset_detail', kwargs={'pk': self.sigla})

    def get_members_count(self):
        # count members by band
        # conta os membros por banda
        return self.asset.count()

    def to_dict_json(self):
        data = {
            'sigla': self.sigla,
            'name': self.name,
            'price': self.price,
            'classe': self.classe,
            'setor': self.setor,
            'subsetor': self.subsetor,
            'segmento': self.segmento,
        }
        return data

app/financedb/apps/asset/views.py
import math
from django.http.response import JsonResponse
from django.shortcuts import render, redirect
from django.http import Http404
from django.core.files.storage import FileSystemStorage
from .form import AssetForm
from .models import Asset

# Create your views here.


def list_assets(request):
    # data['transactions'] = Transaction.objects.all()
    assets = Asset.objects.all()
    search = request.GET.get('search')
    if search:
        assets = Asset.objects.filter(name__icontains=search)
    return render(request, 'list_assets.html', {'objects': assets})


def detail_asset(request, pk):
    try:
        asset = Asset.objects.get(pk=pk)
    except Asset.DoesNotExist:
        raise Http404('asset does not exist')
    return render(request, 'detail_asset.html', {'object': asset})


def new_asset(request):
    form = AssetForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('url_list_assets')
    else:
        print("Deu errado")
    return render(request, 'new_asset.html', {'form': form})


def update_asset(request, pk):
    try:
        asset = Asset.objects.get(pk=pk)
    except Asset.DoesNotExist:
        raise Http404('asset does not exist')

    form = AssetForm(request.POST or None, instance=asset)
    if form.is_valid():
        form.save()
        return redirect('url_list_assets')
    else:
        print("Deu errado")
    return render(request, 'new_asset.html', {'form': form, 'asset': asset})


def delete_asset(request, pk):
    try:
        asset = Asset.objects.get(pk=pk)
    except Asset.DoesNotExist:
        raise Http404('asset does not exist')
    asset.delete()
    return redirect('url_list_assets')


def assets_json1(request):
    assets = Asset.objects.all()
    data = [asset.to_dict_json() for asset in assets]
    return JsonResponse({'data': data})


def assets_json(request):
    assets = Asset.objects.all()
    total = assets.count()

    _start = request.GET.get('start')
    _length = request.GET.get('length')
    if _start and _length:
        start = int(_start)
        length = int(_length)
        page = math.ceil(start / length) + 1  # [opcional]
        per_page = length  # [opcional]

        assets = assets[start:start + length]

    data = [asset.to_dict_json() for asset in assets]
    response = {
        'data': data,
        # 'page': page,  # [opcional]
        # 'per_page': per_page,  # [opcional]
        'recordsTotal': total,
        'recordsFiltered': total,
    }
    return JsonResponse(response)


def assets_serverside(request):
    template_name = 'assets_serverside.html'
    return render(request, template_name)

app/financedb/apps/asset/templates/assets_serverside.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}

<div class="page-header">
  <h2>Lista de ativos cadastrados
    <span class="pull-right">
      <a href="{% url 'asset:url_new_asset'%}">
        <button type="button" class="btn btn-primary">
          <span class="fa fa-plus"></span> Adicionar
        </button>
      </a>
    </span>
  </h2>

  <div class="container">
    <div class="row">
      <div class="cols">
        <h2>DataTables Server-side render </h2>
        <table id="AssetsTable1" class="table">
          <thead>
            <tr>
              <th class="text-center">Ativo</th>
              <th>Nome</th>
              <th>Preço</th>
              <th>Classe</th>
              <th>Setor</th>
              <th>Subsotor</th>
              <th>Segmento</th>
            </tr>
          </thead>
        </table>
      </div>
    </div>

    <hr>

  </div> <!-- /container -->
</div>

{% endblock content %}

{% block js %}

<script src="{% static 'js/data.js' %}"></script>

{% endblock js %}

app/financedb/apps/asset/templates/detail_asset.html
{% extends "core/base.html"%}

{% block content %}

<a href="{% url 'asset:url_list_assets' %}">Voltar</a>

<h1>{{ object }}
  <span class="pull-right">
    <a href="{% url 'asset:url_update_asset' object.sigla %}">
      <button type="button" class="btn btn-success">
        <span class="fa fa-pencil"></span> Editar
      </button>
    </a>
  </span>
</h1>

<div class="col-sm-6">
  <table class="table table-user-information">
    <tbody>
      <tr>
        <th class="text-right">Ativo</th>
        <td>{{ object.sigla }}</td>
      </tr>
      <tr>
        <th class="text-right">Codigo</th>
        <td>{{ object.symbol }}</td>
      </tr>
      <tr>
        <th class="text-right">Nome</th>
        <td>{{ object.name }}</td>
      </tr>
      <tr>
        <th class="text-right">Preço</th>
        <td>R$ {{ object.price }}</td>
      </tr>
      <tr>
        <th class="text-right">Classe</th>
        <td>{{ object.classe }}</td>
      </tr>
      <tr>
        <th class="text-right">Setor</th>
        <td>{{ object.setor }}</td>
      </tr>
      <tr>
        <th class="text-right">Subsotor</th>
        <td>{{ object.subsetor }}</td>
      </tr>
      <tr>
        <th class="text-right">Segmento</th>
        <td>{{ object.segmento }}</td>
      </tr>
      <tr>
        <th class="text-right">Razão Social</th>
        <td>{{ object.razao_social }}</td>
      </tr>
      <tr>
        <th class="text-right">CNPJ</th>
        <td>{{ object.cnpj }}</td>
      </tr>
    </tbody>
  </table>
</div>

{% endblock content %}

app/financedb/apps/asset/templates/list_assets.html
{% extends "core/base.html"%}
{% load static %}

{% block content %}

<div class="row">
  <div class="col-sm-6">
    <form action="." method="GET" class="form-inline">
      <input type="text" id="search" name="search" class="form-control" placeholder="Busca">
      <input type="submit" class="btn btn-primary" style="margin-left: 10px;" value="OK">
    </form>
  </div>
</div>

<div class="page-header">
  <h2>Lista de ativos cadastrados
    <span class="pull-right">
      <a href="{% url 'asset:url_new_asset'%}">
        <button type="button" class="btn btn-primary">
          <span class="fa fa-plus"></span> Adicionar
        </button>
      </a>
    </span>
  </h2>

  {% if objects %}
    {% comment %} <h1>Lista de ativos cadastrados</h1> {% endcomment %}
    <table id="AssetsTable" class="table table-striped">
      <thead>
        <tr>
          <th class="text-center">Ativo</th>
          <th>Nome</th>
          <th>Preço</th>
          <th>Classe</th>
          <th>Setor</th>
          <th>Subsotor</th>
          <th>Segmento</th>
        </tr>
      </thead>
      <tbody>
        {% for object in objects %}
          <tr>
            <td class="text-center"> <a 
            href="{% url 'asset:url_asset_detail' object.sigla %}"
            >{{object.sigla}}</a></td>
            <td>{{object.name}}</td>
            <td>{{object.price}}</td>
            <td>{{object.classe}}</td>
            <td>{{object.setor}}</td>
            <td>{{object.subsetor}}</td>
            <td>{{object.segmento}}</td>
          </tr> 
        {% endfor %}
      </tbody>
    </table>

  {% else %}
    <p class="alert alert-warning">Sem itens na lista.</p>
  {% endif %}

</div>

{% endblock content %}

{% block js %}

<script src="{% static 'js/data.js' %}"></script>

{% endblock js %}

app/financedb/apps/asset/templates/new_asset.html
{% extends "core/base.html"%}

{% block content %}
  <h1>Novo ativo</h1>
  <form method="post" >
    {% csrf_token %}
    {{form.as_p}}
    <button class="btn btn-primary" type="submit">Salvar</button>
    {% if asset %}
      <a href="{% url 'asset:url_delete_asset' asset.sigla %}">Remover</a>
    {% endif %}
  </form>
{% endblock content %}