app/financedb/apps/asset/urls.py
from django.urls import path
from . import views as v

app_name = 'asset'


urlpatterns = [

    path('serverside/', v.assets_serverside,
         name='url_assets_serverside'),
    path('list/', v.list_assets, name='url_list_assets'),
    path('detail/<str:pk>/', v.detail_asset, name='url_asset_detail'),
    path('update/<str:pk>/', v.update_asset, name='url_update_asset'),
    path('delete/<str:pk>/', v.delete_asset, name='url_delete_asset'),
    path('new/', v.new_asset, name='url_new_asset'),
    path('json/', v.assets_json, name='url_assets_json'),

]

app/financedb/apps/portfolio/urls.py
from django.urls import include, path
from . import views as v

app_name = 'portfolio'


# entrada_patterns = [
#     path('', v.EstoqueEntradaList.as_view(), name='estoque_entrada_list'),
#     path('add/', v.estoque_entrada_add, name='estoque_entrada_add'),
# ]

# saida_patterns = [
#     path('', v.EstoqueSaidaList.as_view(), name='estoque_saida_list'),
#     path('add/', v.estoque_saida_add, name='estoque_saida_add'),
# ]

urlpatterns = [

    path('list', v.list_portfolio, name='url_list_portfolio'),
    # path('<int:pk>/', v.EstoqueDetail.as_view(), name='estoque_detail'),
    # path('entrada/', include(entrada_patterns)),
    # path('saida/', include(saida_patterns)),
]

app/financedb/apps/transaction/urls.py
from django.urls import path
from . import views as v

app_name = 'transaction'


urlpatterns = [

    path('list/', v.list_transactions,
         name='url_list_transactions'),
    path('new/', v.Create_transaction.as_view(),
         name='url_new_transaction'),
    path('update/<int:pk>/',
         v.Update_transaction.as_view(), name='url_update_transaction'),
    path('detail/<int:pk>/',
         v.detail_transaction, name='url_detail_transaction'),
    path('delete/<int:pk>/',
         v.delete_transaction, name='url_delete_transaction'),

    path('test/', v.test, name='url_test'),
    path('serverside/', v.transactions_serverside,
         name='url_transactions_serverside'),
    path('json/', v.transactions_json,
         name='url_transactions_json'),


]

app/financedb/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('', include('financedb.apps.core.urls')),
    path('asset/', include('financedb.apps.asset.urls')),
    path('transaction/', include('financedb.apps.transaction.urls')),
    path('portfolio/', include('financedb.apps.portfolio.urls')),

    path('admin/', admin.site.urls),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

app/financedb/apps/portfolio/models.py
from django.db import models
# from asset.models import Asset
# from nota.models import Nota

# # Create your models here.
# # Transform tabela em view no database


# class Portfolio(models.Model):
#     """A model of a Transactions."""
#     # id = models.IntegerField(primary_key=True) #models.AutoField(primary_key=True)
#     asset = models.ForeignKey(
#         Asset, related_name='asset', on_delete=models.CASCADE)
#     position = models.DecimalField(
#         max_digits=10, decimal_places=5, null=True, blank=True, default=0)
#     avg_price = models.DecimalField(max_digits=10, decimal_places=5)
#     cost_basic = models.DecimalField(max_digits=10, decimal_places=5)
#     mkt_value = models.DecimalField(max_digits=10, decimal_places=5)
#     profit = models.DecimalField(max_digits=10, decimal_places=5)
#     percent = models.DecimalField(max_digits=10, decimal_places=5)
#     last_update = models.DateTimeField(auto_now_add=True)

#     class Meta:
#         ordering = ('mkt_value',)
#         verbose_name = 'portifolio'

#     # def __str__(self):
#     #     return self.id
#     def __str__(self):
#         return '{} - {}'.format(self.pk, self.asset)

app/financedb/apps/portfolio/views.py
from django.shortcuts import render
from financedb.apps.transaction.models import Transaction
from financedb.apps.asset.models import Asset
from django.db.models import Sum, Avg

# Create your views here.


def list_portfolio(request):
    # data['transactions'] = Transaction.objects.all()
    # portfolio = Transaction.objects.all()
    data = []
    objects = []
    asset = Asset.objects.all()
    transactions = Transaction.objects.order_by('asset').values(
        'asset').annotate(Sum('amount'), Avg('price'))
    for pos in transactions:
        if pos['amount__sum'] > 0:
            data = dict(
                asset=pos['asset'],
                position="{:.2f}".format(pos['amount__sum']),
                avg_price="{:.2f}".format(pos['price__avg']),
                cost_basic=0,
                mkt_value=0,
                profit=0,
                percent=0,
            )
            objects.append(data)

    return render(request, 'list_portfolio.html',
                  {'objects': objects, 'asset': asset})

app/financedb/apps/portfolio/templates/list_portfolio.html
{% extends "core/base.html"%}
{% load static %}

{% block content %}

<div class="row">
  <div class="col-sm-6">
    <form action="." method="GET" class="form-inline">
      <input type="text" id="search" name="search" class="form-control" placeholder="Busca">
      <input type="submit" class="btn btn-primary" style="margin-left: 10px;" value="OK">
    </form>
  </div>
</div>

<div class="page-header">
  <h2>Lista de Portifolio
    <span class="pull-right">
      <a href="{% url 'transaction:url_new_transaction'%}">
        <button type="button" class="btn btn-primary">
          <span class="fa fa-plus"></span> Adicionar
        </button>
      </a>
    </span>
  </h2>

  {% if objects %}
    {% comment %} <h1>Lista de ativos cadastrados</h1> {% endcomment %}
    <table id="TransactionsTable" class="table table-striped">
      <thead>
        <tr>
          <th class="text-center">Ativo</th>
          <th class="text-center">Quantidade</th>
          <th class="text-center">Preço medio</th>
          <th class="text-center">Custo de aquisição</th>
          <th class="text-center">Valor de mecado</th>
          <th class="text-center">Lucro</th>
          <th class="text-center">Percentual</th>
        </tr>
      </thead>
      <tbody>
        {% for object in objects %}
          <tr>
            <td> <a href="{% url 'asset:url_asset_detail' object.asset %}" 
                    >{{object.asset}}</a></td> 
            <td>{{object.position}}</td> 
            <td>{{object.avg_price}}</td> 
            <td>R$ {{object.cost_basic}}</td>
            <td>R$ {{object.mkt_value}}</td>
            <td class="text-center">R$  {{object.profit}}</td>
            <td class="text-center"> {{object.percent}} </td>
          </tr> 
        {% endfor %}
      </tbody>
    </table>

  {% else %}
    <p class="alert alert-warning">Sem itens na lista.</p>
  {% endif %}

</div>

{% endblock content %}

{% block js %}

<script src="{% static 'js/data.js' %}"></script>

{% endblock js %}